---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    export_base_dir: "aap_migration_backups/"
  collections:
    - redhat_cop.aap2_migrate
  tasks:
  - name: Import backup role
    import_role:
      name: aap2_migrate

