---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    export_base_dir: "aap_migration_backups/"
  collections:
    - ansible.controller
    - redhat_cop.aap2_migrate
  tasks:
  - name: Get NetApp info (Password Authentication)
    na_ontap_gather_facts:
      state: info
      hostname: "na-vsim"
      username: "admin"
      password: "admins_password"
  - debug:
      var: ontap_facts
  - name: Import backup role
    import_role:
      name: aap2_migrate

