---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: true
  collections:
    - ansible_refarch.aap2_migrate
  tasks:
  - name: Import backup role
    import_role:
      name: aap2_migrate

