---
- name: Import Objects
  hosts: localhost
  connection: local
  gather_facts: true
  collections:
    - ansible_refarch.aap2_migrate
  tasks:
  - name: Import backup role
    import_role:
      name: migrate
      tasks_from: 50_controller_import.yml

