---
- name: "Git repo: is it up-to-date?"
  git:
    repo: "{{ gh_repo }}"
    dest: "./{{ export_base_dir_import }}"
    update: yes
    version: master
  register: git
  ignore_errors: True

- name: Import Objects(processed for AAP2.1)
  ansible.controller.import:
    assets: "{{ lookup('file', '{{ export_base_dir_import }}/latest/controller/{{ item }}.yml') | from_yaml() }}"
  loop:
    - orgs
    - users
    - teams
    - projects
    - inventory
    - credentials
    - job_templates
    - workflow_templates
  register: import_results

