---

- name: Sync Community Repo
  ansible.builtin.uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST
    force_basic_auth: true
    validate_certs: false

- name: Verify Community Repo Sync Completed
  ansible.builtin.uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/community/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: false
    force_basic_auth: true
  register: communitystatus
  until: communitystatus.json.last_sync_task.state == "completed"
  retries: 80
  delay: 20

- name: Sync Certified Repo
  ansible.builtin.uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    method: POST
    force_basic_auth: true
    validate_certs: false

- name: Verify rh-certified Repo Sync Completed
  ansible.builtin.uri:
    url: https://towerpah.shadowman.dev/api/galaxy/content/rh-certified/v3/sync/config/
    user: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    validate_certs: false
    force_basic_auth: true
  register: certifiedstatus
  until: certifiedstatus.json.last_sync_task.state == "completed"
  retries: 80
  delay: 20
