---
- name: Export Projects
  ansible.controller.export:
    projects: all
  register: __export_projects

- name: Export users
  ansible.controller.export:
    users: all
  register: __export_users

- name: Export tower objects 
  copy:
    content: "{{ item[0].assets | to_nice_yaml() }}"
    dest: "{{ __export_tower_dir }}/{{ item[1] }}.yml"
  loop: "{{ [ '{{ __export_projects }}', '{{ __export_users }}' ] | zip([ 'projects', 'users']) | list }}"

#- name: Export tower objects 
#  copy:
#    content: "{{ item[0].assets | to_nice_yaml() }}"
#    dest: "{{ __export_tower_dir }}/{{ item[1] }}.yml"
#  loop: "{{ [ \"{{ __export_projects }}\", \"{{ __export_users }}\", \"{{ __export_teams }}\", \"{{ __export_orgs }}\", \"{{ __export_inventory }}\", \"{{ __export_credentials }}\", \"{{ __export_job_templates }}\", \"{{ __export_workflow_templates }}\" ] | product([ 'projects', 'users', 'teams', 'orgs', 'inventory', 'credentials', 'job_templates', 'workflow_templates' ]) | list }}"
