---
- name: Export controlller objects 
  copy:
    content: "{{ item[0].assets | redhat_cop.aap2_migrate.aap1toaap2 | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/{{ item[1] }}.yml"
  loop: >
    "{{ [ 
    \"{{ __export_projects }}\",
    \"{{ __export_users }}\",
    \"{{ __export_teams }}\",
    \"{{ __export_orgs }}\",
    \"{{ __export_inventory }}\",
    \"{{ __export_credentials }}\",
    \"{{ __export_job_templates }}\",
    \"{{ __export_workflow_templates }}\" ] | product([ 
    'projects',
    'users',
    'teams',
    'orgs',
    'inventory',
    'credentials',
    'job_templates',
    'workflow_templates' ]) | list }}"

- name: Export projects
  copy:
    content: "{{ __export_projects.assets| redhat_cop.aap2_migrate.aap1toaap2  | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/projects.yml"

- name: Export users
  copy:
    content: "{{ __export_users.assets | redhat_cop.aap2_migrate.aap1toaap2 | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/users.yml"

- name: Export teams
  copy:
    content: "{{ __export_teams.assets | redhat_cop.aap2_migrate.aap1toaap2 | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/teams.yml"

- name: Export orgs
  copy:
    content: "{{ __export_orgs.assets | redhat_cop.aap2_migrate.aap1toaap2 | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/orgs.yml"

- name: Export inventory
  copy:
    content: "{{ __export_inventory.assets | redhat_cop.aap2_migrate.aap1toaap2 |to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/inventory.yml"
    
- name: Export Credentials
  copy:
    content: "{{ __export_credentials.assets | redhat_cop.aap2_migrate.aap1toaap2 |to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/credentials.yml"

- name: Export workflow job template to file
  copy:
    content: "{{ __export_job_templates.assets | redhat_cop.aap2_migrate.aap1toaap2 | to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/job_templates.yml"

- name: Export workflow job template to file
  copy:
    content: "{{ __export_workflow_templates.assets | redhat_cop.aap2_migrate.aap1toaap2 |to_nice_yaml() }}"
    dest: "{{ __export_controller_dir }}/workflow_templates.yml"
