---
- name: Setup the Git repo locally
  include_tasks: 10_setup_git_repo.yml

- name: Take a local backup of export of objects from AAP 1.2
  include_tasks: 20_tower_backup.yml

- name: Take a local backup of export of objects for AAP 2.1(cleansed mode)
  include_tasks: 30_export_cleansed_tower.yml

- name: Git push both copies to the git repo
  include_tasks: 40_git_push.yml
