---
- name: Check if local changes exist in git
  shell: git status
  args:
    chdir: "./{{ migrate_export_base_dir }}"
  register: git_status
- debug:
    var: git_status

- name: Git rm latest file
  file:
    path: "./{{ migrate_export_base_dir }}latest"
    state: absent
- name: Create latest that symlinks to the this run
  ansible.builtin.file:
    src: "{{ ansible_date_time.date }}"
    dest: "{{ migrate_export_base_dir }}latest"
    state: link
- name: Git add latest file
  shell: "git add latest"
  args:
    chdir: "./{{ migrate_export_base_dir }}"
  register: gitadd_latest
- debug:
    var: gitadd_latest
- name: Git - Adding
  shell: "git add *"
  args:
    chdir: "./{{ migrate_export_base_dir }}"
  register: gitadd
  when: '"untracked files present" in git_status.stdout or "Changes not staged for commit" in git_status.stdout'
- debug:
    var: gitadd
- name: Git - commiting
  shell: git commit -m "Ansible migration Backup {{ ansible_date_time.date }}"
  args:
    chdir: "./{{ migrate_export_base_dir }}"
  register: gitcommit
  when: '"untracked files present" in git_status.stdout or "Changes not staged for commit" in git_status.stdout'
- debug:
    var: gitcommit.stdout
- name: Git - push
  shell: git push
  args:
    chdir: "./{{ migrate_export_base_dir }}"
  register: gitpush
  when: '"untracked files present" in git_status.stdout or "Changes not staged for commit" in git_status.stdout'
- debug:
    var: gitpush
