---
- name: "Git repo: is it up-to-date?"
  git:
    repo: "{{ gh_repo }}"
    dest: "./{{ migrate_import_base_dir }}"
    update: yes
    version: master
  register: git
  ignore_errors: True
  tags: always

- name: Import Objects phase1(processed for AAP2.1)
  ansible.controller.import:
    assets: "{{ lookup('file', '{{ migrate_import_base_dir }}/latest/controller/{{ item }}.yml') | from_yaml() }}"
  loop:
    - orgs
    - users
    - teams
  tags: phase1

- name: Import Objects phase2(processed for AAP2.1)
  ansible.controller.import:
    assets: "{{ lookup('file', '{{ migrate_import_base_dir }}/latest/controller/{{ item }}.yml') | from_yaml() }}"
  loop:
    - projects
    - inventory
    - credentials
    - job_templates
    - workflow_templates
  tags: phase2

