namespace: ansible_refarch
name: aap2_migrate
version: 1.0.0
readme: README.md
authors:
- Anshul Behl <abehl@redhat.com>
description: Collection to help in migration from AAP1 to AAP2
license:
- GPL-2.0-or-later
tags:
  - migration
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []

