- block:
  - name: Install podman on localhost
    dnf:
      name: podman
      state: present
  - name: Download the default EE on localhost
    containers.podman.podman_image:
      name: "{{ default_ee_url }}"
      username: "{{ registry_username }}"
      password: "{{ registry_password }}"
  - name: Get pip list from Default EE
    ansible.builtin.command: "podman run --rm -it {{ default_ee_url }} bash -c \"/bin/pip3 freeze\""
    register: ee_pip_list_output
  - name: Retain the EE pip list without package versions
    set_fact:
      ee_pip_list: "{{ ee_pip_list_output.stdout.split('\n') | map('regex_replace', '(\\w+)==([\\d+\\.]+).*', '\\1') | list }}"
  - name: Check what's extra in venv and create a requirement list for the new EE
    set_fact:
      extra_deps: "{{ combined_requirements | difference(ee_pip_list) }}"
  - name: Show the packages that are extra from default EEs in custom venvs combined.
    debug:
      msg: "{{ extra_deps }}"
  delegate_to: localhost
